### ISSUE TITLE
error in inference

### ISSUE THREAD

**Issue by JINXER000** [UM-ARM-Lab/Efficient-Eng-2-LTL#4]
Hi Author, 

Thanks for your code. I follow your instructions on installation and training, everything works fine. However, in inference stage, I came across this problem:

```
Last test_datum: FullDatum(dialogue_id='eval-0', turn_part_index=None, agent_context=None, natural='go to the twond floor avoiding the purple room . if you reached the third floor you can stay there , or head to the purple room .', canonical='until ( not ( the purple room ) , the third floor )') in experiment ltl_Bart_test-full_drone-syn-aug_constrained_utterance_train-0
Traceback (most recent call last):
  File "/home/uas/ltl/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/model.py", line 366, in predict
    results = await beam_search(
  File "/home/uas/ltl/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/search.py", line 388, in beam_search
    for node, per_node_expansion in await asyncio.gather(
  File "/home/uas/ltl/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/search.py", line 381, in expand
    expansions = await problem.expand(node)
  File "/home/uas/ltl/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/search.py", line 219, in expand
    indices[topk_eligible_logprobs.indices],
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/uas/ltl/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/run_exp.py", line 231, in run
    async for kbest, test_datum in limits.map_async_limited(
  File "/home/uas/ltl/Efficient-Eng-2-LTL/run/semantic_parsing_with_constrained_lm/async_tools/limits.py", line 237, in map_async_limited
    raise MapInnerException(orig_item) from exc
semantic_parsing_with_constrained_lm.async_tools.limits.MapInnerException: FullDatum(dialogue_id='eval-0', turn_part_index=None, agent_context=None, natural='go to the twond floor avoiding the purple room . if you reached the third floor you can stay there , or head to the purple room .', canonical='until ( not ( the purple room ) , the third floor )')

```
I have no idea what will cause data to be distributed on different devices. Has anyone experienced a similar error?

**Comment by Jiayi-Pan** [comment]
Thank you for your interests in this project! Could you share more details about the hardware and system environment you're using? 

It looks to be a straightforward error related to the tensor being on the wrong device. You might be able to quickly fix this by adding `topk_eligible_logprobs.indices.to('cuda')` before the line causing the error."
