### ISSUE TITLE
inference  step error

### ISSUE THREAD

**Issue by Echo-b** [UM-ARM-Lab/Efficient-Eng-2-LTL#6]
Hi,  thanks for the excellent work.

When I tried to do the inference as stated in the readme.txt, I run the command:
```
python -m semantic_parsing_with_constrained_lm.run_exp --config-name semantic_parsing_with_constrained_lm.configs.ltl_config --log-dir logs/ --model Bart --eval-split test-full --exp-names "ltl_Bart_test-full_pick-syn-aug_constrained_utterance_train-0"
```

Then I get some output: 
```
Entire model to GPU 0
********************
Running ltl_Bart_test-full_pick-syn-aug_constrained_utterance_train-0 rank 0 world size 1
********************
Total test examples: 744
Test examples this shard: 744
```

And next I entered  a runtime error raised:

```
Last test_datum: FullDatum(dialogue_id='eval-0', turn_part_index=None, agent_context=None, natural='move the arm to the block and pick it up next placing it in the bin and coming back to pick up the next block', canonical='globally ( and ( until ( scan , not ( any cubes ) ) , finally ( any cubes ) ) )') in experiment ltl_Bart_test-full_pick-syn-aug_constrained_utterance_train-0
Traceback (most recent call last):
  File "E:\Work\LLM2LTL\Efficient-Eng-2-LTL\run\semantic_parsing_with_constrained_lm\model.py", line 366, in predict
    results = await beam_search(
  File "E:\Work\LLM2LTL\Efficient-Eng-2-LTL\run\semantic_parsing_with_constrained_lm\search.py", line 388, in beam_search
    for node, per_node_expansion in await asyncio.gather(
  File "E:\Work\LLM2LTL\Efficient-Eng-2-LTL\run\semantic_parsing_with_constrained_lm\search.py", line 381, in expand
    expansions = await problem.expand(node)
  File "E:\Work\LLM2LTL\Efficient-Eng-2-LTL\run\semantic_parsing_with_constrained_lm\search.py", line 219, in expand
    indices[topk_eligible_logprobs.indices],
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\Work\LLM2LTL\Efficient-Eng-2-LTL\run\semantic_parsing_with_constrained_lm\run_exp.py", line 228, in run
    async for kbest, test_datum in limits.map_async_limited(
  File "E:\Work\LLM2LTL\Efficient-Eng-2-LTL\run\semantic_parsing_with_constrained_lm\async_tools\limits.py", line 237, in map_async_limited
    raise MapInnerException(orig_item) from exc
semantic_parsing_with_constrained_lm.async_tools.limits.MapInnerException: FullDatum(dialogue_id='eval-0', turn_part_index=None, agent_context=None, natural='move the arm to the block and pick it up next placing it in the bin and coming back to pick up the next block', canonical='globally ( and ( until ( scan , not ( any cubes ) ) , finally ( any cubes ) ) )')
```

I tried to solve the error by adding `topk_eligible_logprobs.indices.to('cuda')` before the line causing the error but didn't work.  can you give me some specific advice to solve this? Any idea is appreciated. Thanks!

I have a 4060ti GPU and the training phase is good.

**Comment by Jiayi-Pan** [comment]
Hi, maybe you should move `indices` to cuda

**Comment by Echo-b** [comment]
Thanks, I modified lines 197 to 222 of the `search.py` file concerning the `indices` section of the code.

```python
 if allowed_next is None:
            indices = torch.arange(next_logprobs.shape[0]).cuda()
            eligible_logprobs = next_logprobs
        else:
            indices = allowed_next.cuda()
            eligible_logprobs = next_logprobs[allowed_next]

        if self.top_k is None:
            token_and_logprob_iter = (
                # .item() converts 0D tensor to a Python number
                (token_id_tensor.item(), logprob)  # type: ignore
                for token_id_tensor, logprob in zip(indices.cuda(), eligible_logprobs)
            )
        else:
            topk_eligible_logprobs = torch.topk(
                eligible_logprobs,
                k=min(self.top_k, eligible_logprobs.shape[0]),
                sorted=False,
            )
            token_and_logprob_iter = (
                (token_id_tensor.item(), logprob)  # type: ignore
                for token_id_tensor, logprob in zip(
                    indices[topk_eligible_logprobs.indices.cuda()],
                    topk_eligible_logprobs.values,
                )
            )
```
 After these changes, it can now run properly.

```
Current test index: 744
Timing report:
- Items processed: 332
- Elapsed: 216.11402487754822
- Per item: 0.6509458580649042
logs\ltl_Bart_test-full_pick-syn-aug_constrained_utterance_train-0\results.json {
    "exact_match/top1": 0.7459677419354839,
    "exact_match/top2": 0.8064516129032258,
    "exact_match/top3": 0.8790322580645161,
    "exact_match/top4": 0.9314516129032258,
    "exact_match/top5": 1.0,
    "exact_match/top6": 1.0,
    "exact_match/top7": 1.0,
    "exact_match/top8": 1.0,
    "exact_match/top9": 1.0,
    "exact_match/top10": 1.0,
    "denotation/top1": 1.0,
    "denotation/top2": 1.0,
    "denotation/top3": 1.0,
    "denotation/top4": 1.0,
    "denotation/top5": 1.0,
    "denotation/top6": 1.0,
    "denotation/top7": 1.0,
    "denotation/top8": 1.0,
    "denotation/top9": 1.0,
    "denotation/top10": 1.0
}

```
